language: java

jdk:
  - oraclejdk8
  
git:
  depth: false

notifications:
  email:
    recipients:
      - process@snappydata.io
  
# whitelist
branches:
  only:
    - trilok_travis_ci
    - master
    
sudo: false 

script: 
  ./gradlew precheckin
