site_name: SnappyData Docs - Preview release
site_url: http://www.snappydata.io
site_description: Project documentation with Markdown.
site_author: SnappyData development team

repo_url: https://github.com/SnappyDataInc/snappydata

pages:
- Table of Contents: index.md
# this file may just be the [toc] tag .. not sure if that works.
#
- Getting Started: README.md
- Building from source, project layout: build-instructions.md
- Overview: snappyIntroduction.md
- Key features: features.md
- Architecture: architecture.md
- Configuring the cluster: configuration.md
- Connecting using JDBC, Spark: connectingToCluster.md
- Developing Apps using the Spark API: jobs.md
- Row and Column tables: rowAndColumnTables.md
- Approximate query processing: aqp.md
- Stream processing using SQL: streamingWithSQL.md
- Deployment topologies: deployment.md
- About:
#   - Release Notes: about/release-notes.md
#   - Contributing: about/contributing.md
    - License: LICENSE.md

theme: readthedocs

markdown_extensions:
    - toc:
        permalink: True
    - admonition:

copyright: Copyright &copy; 2016 <a href="http://snappydata.io</a>.
#google_analytics: ['UA-64703291-1', 'snappydata.io']
