site_name: SnappyData Docs - Preview release
site_url: http://www.snappydata.io
site_description: Project documentation with Markdown.
site_author: SnappyData development team
site_favicon: favicon.ico

repo_url: https://github.com/SnappyDataInc/snappydata

pages:
# this file may just be the [toc] tag .. not sure if that works.
#
- Getting Started: index.md
- Building from source, project layout: featureDocs/build-instructions.md
- Overview: featureDocs/snappyIntroduction.md
- Key features: featureDocs/features.md
- Architecture: featureDocs/architecture.md
- Configuring the cluster: featureDocs/configuration.md
- Connecting using JDBC, Spark: featureDocs/connectingToCluster.md
- Developing Apps using the Spark API: featureDocs/jobs.md
- Row and Column tables: featureDocs/rowAndColumnTables.md
- Approximate query processing: featureDocs/aqp.md
- Stream processing using SQL: featureDocs/streamingWithSQL.md
- Deployment topologies: featureDocs/deployment.md
- About:
#   - Release Notes: about/release-notes.md
#   - Contributing: about/contributing.md
    - License: featureDocs/LICENSE.md

theme: readthedocs

extra_css: [extra.css]

copyright: Copyright &copy; 2016 <a href="http://snappydata.io</a>.
#google_analytics: ['UA-64703291-1', 'snappydata.io']
