site_name: SnappyData Documentation
site_url: http://www.snappydata.io
site_description: Project documentation for SnappyData
site_author: SnappyData Team
site_favicon: favicon.ico

repo_url: https://github.com/SnappyDataInc/snappydata

pages:
# this file may just be the [toc] tag .. not sure if that works.
#
- Overview: index.md
# - Introduction: snappyIntroduction.md
- 'Getting Started in 5 minutes or Less': 'quickstart.md'
- 'Getting Started in 5 minutes or Less': 
    - 'Getting Started with your Spark Distribution': 'quickstart/getting_started_with_your_spark_distribution.md'
    - 'Getting Started by Installing SnappyData On-Premise': 'quickstart/getting_started_by_installing_snappydata_on-premise.md'
    - 'Getting Started with Docker Image': 'quickstart/getting_started_with_docker_image.md'
    - 'Using Spark Scala APIs': 'quickstart/using_spark_scala_apis.md'
    - 'SnappyData Performance:16x-20x faster than Apache Spark': 'quickstart/performance_apache_spark.md'
    - 'Using SQL': 'quickstart/using_sql.md'
- 'Download and Install': 'install.md'
- 'Download and Install':
    - System Requirements: 'install/system_requirements.md'
    - 'Install On-Premise': 'install/install_on_premise.md'
    - 'Setting up Cluster on Amazon Web Services': 'install/setting_up_cluster_on_amazon_web_services.md'
    - 'Building from Source': 'install/building_from_source.md'
    - 'Upgrade Instructions (1.0.0 to 1.0.1)': 'install/upgrade.md'
#- 'How Tos': 'howto.md'
#- 'How Tos': 
#    - 'How to Start a SnappyData Cluster': 'howto/start_snappy_cluster.md'
#    - 'How to Check the Status of a SnappyData Cluster': 'howto/check_status_cluster.md'
#    - 'How to Stop a SnappyData Cluster': 'howto/stop_snappy_cluster.md'
#    - 'How to Run Spark Job inside the Cluster': 'howto/run_spark_job_inside_cluster.md'
#    - 'How to Access SnappyData Store from existing Spark Installation using Smart Connector': 'howto/spark_installation_using_smart_connector.md'
#    - 'How to Use Snappy SQL shell (snappy-sql)': 'howto/use_snappy_shell.md'
#    - 'How to Create Row Tables and Run Queries': 'howto/create_row_tables_and_run_queries.md'
#    - 'How to Create Column Tables and Run Queries': 'howto/create_column_tables_and_run_queries.md'
#    - 'How to Load Data into SnappyData Tables': 'howto/load_data_into_snappydata_tables.md'
#    - 'How to Load Data from External Data Stores (e.g. HDFS, Cassandra, Hive, etc)': 'howto/load_data_from_external_data_stores.md'
#    - 'How to Perform a Colocated Join': 'howto/perform_a_colocated_join.md'
#    - 'How to Connect using JDBC Driver': 'howto/connect_using_jdbc_driver.md'
#    - 'How to Store and Query JSON Objects': 'howto/store_and_query_json_objects.md'
#    - 'How to Store and Query Objects': 'howto/store_and_query_objects.md'
#    - 'How to use Stream Processing with SnappyData': 'howto/use_stream_processing_with_snappydata.md'
#    - 'How to use Transactions Isolation Levels': 'howto/use_transactions_isolation_levels.md'
#    - 'How to use Synopsis Data Engine to Run Approximate Queries': 'howto/use_synopsis_data_engine_to_run_approximate_queries.md'
#    - 'How to use Python to Create Tables and Run Queries': 'howto/use_python_to_create_tables_and_run_queries.md'
#    - 'How to Connect using ODBC Driver': 'howto/connect_using_odbc_driver.md'
#    - 'How to Connect to the Cluster from External Network': 'howto/connect_to_the_cluster_from_external_clients.md'
#    - 'How to Import Data from Hive Table into SnappyData Table': 'howto/import_from_hive_table.md'    
#    - 'How to Export and Restore Table Data using HDFS': 'howto/export_hdfs.md'    
#    - 'How to Use Apache Zeppelin with SnappyData': 'howto/use_apache_zeppelin_with_snappydata.md'
#    - 'How to Configure Apache Zeppelin to Securely and Concurrently access the SnappyData Cluster': 'howto/concurrent_apache_zeppelin_access_to_secure_snappydata.md'
- 'Architecture': 'architecture.md'
- 'Architecture': 
    - 'Core Components': 'architecture/core_components.md'
    - 'Data Ingestion Pipeline': 'architecture/data_ingestion_pipeline.md'
    - 'Hybrid Cluster Manager': 'architecture/hybrid_cluster_manager.md'
    - 'SnappyData Cluster Architecture': 'architecture/cluster_architecture.md'    
- 'Configuring the Cluster': 'configuration.md'
- 'Configuring the Cluster':
    - 'Configuration': 'configuring_cluster/configuring_cluster.md'
    - 'SSL Setup for Client-Server': 'configuring_cluster/ssl_setup.md'
    - 'List of Properties': 'configuring_cluster/property_description.md'
    - 'Firewalls and Connections': 'configuring_cluster/firewalls_connections.md'
#- 'Programming Guide': 'programming_guide.md'
#- 'Programming Guide':
#    - 'SparkSession, SnappySession and SnappyStreamingContext': 'programming_guide/sparksession_snappysession_and_snappystreamingcontext.md'
#    - 'SnappyData Jobs': 'programming_guide/snappydata_jobs.md'
#    - 'Managing JAR Files': 'programming_guide/managing_jar_files.md'
#    - 'Using SnappyData Shell': 'programming_guide/using_snappydata_shell.md'
#    - 'Using the Spark Shell and spark-submit': 'programming_guide/using_the_spark_shell_and_spark-submit.md'
#    - 'Working with Hadoop YARN cluster Manager': 'programming_guide/working_with_hadoop_yarn_cluster_manager.md'
#    - 'Using JDBC with SnappyData': 'programming_guide/using_jdbc_with_snappydata.md'
#    - 'Multiple Language Binding using Thrift Protocol': 'programming_guide/multiple_language_binding_using_thrift_protocol.md'
#    - 'Building SnappyData Applications using Spark API': 'programming_guide/building_snappydata_applications_using_spark_api.md'
#    - 'Tables in SnappyData': 'programming_guide/tables_in_snappydata.md'
#    - 'Stream Processing using SQL': 'programming_guide/stream_processing_using_sql.md'
#    - 'User Defined Functions (UDF) and User Defined Aggregate Functions (UDAF)': 'programming_guide/udf_and_udaf.md' 
#- 'Distributed Transactions': 'consistency/transactions_about.md'
#- 'Distributed Transactions':
#    - 'How Transactions Work for Row Tables': 'consistency/using_transactions_row.md' 
#    - 'Lock-free Queries using MVCC and Snapshot Isolation for Column Tables': 'consistency/using_snapshot_isolation_column.md'
#- 'Affinity Modes': 'deployment.md'
#- 'Affinity Modes': 
#    - 'Local Mode': 'affinity_modes/local_mode.md'
#    - 'Embedded SnappyData Store Mode': 'affinity_modes/embedded_mode.md'
#    - 'SnappyData Smart Connector Mode': 'affinity_modes/connector_mode.md'
- 'Best Practices': 'best_practices.md'
- 'Best Practices':
    - 'Tuning for Concurrency and Computation': 'best_practices/setup_cluster.md'
    - 'Designing your Database and Schema': 'best_practices/design_schema.md'  
    - 'Designing your Database and Schema':
        - 'Design Principles of Scalable, Partition-Aware Databases': 'best_practices/design_principles.md'
        - 'Optimizing Query Latency: Partitioning and Replication Strategies': 'best_practices/optimizing_query_latency.md'
    - 'Memory Management': 'best_practices/memory_management.md'      
    - 'HA Considerations': 'best_practices/ha_considerations.md'    
    - 'Important Settings': 'best_practices/important_settings.md'
    - 'SnappyData Distributed Transactions': 'best_practices/transactions_best_practices.md'    
#- 'Synopsis Data Engine (SDE)': 'aqp.md'
#- 'Synopsis Data Engine (SDE)': 
#    - 'Key Concepts': 'sde/key_concepts.md'
#    - 'Working with Stratified Samples': 'sde/working_with_stratified_samples.md'
#    - 'Running Queries': 'sde/running_queries.md'
#    - 'More Examples': 'sde/more_examples.md'
#    - 'Sample Selection': 'sde/sample_selection.md'
#    - 'High-level Accuracy Contracts (HAC)': 'sde/hac_contracts.md'
#    - 'Sketching': 'sde/sketching.md'
#- 'Using Database Connectors': 'connectors/connector.md'
#- 'Using Database Connectors':
#    - 'Using the SnappyData CDC (Change Data Capture) Connector': 'connectors/cdc_connector.md'
#- 'Using SnappyData CloudBuilder': 'aqp_aws.md'
#- 'Using SnappyData CloudBuilder': 
#    - 'Key Components': 'isight/key_components.md'
#    - 'Quick Start Steps': 'isight/quick_start_steps.md'
#    - 'The Technology Powering SnappyData CloudBuilder': 'isight/the_technology_powering_isight_cloud.md'
- 'Managing and Monitoring': 'monitoring/managing_and_monitoring.md'
- 'Managing and Monitoring':
    - 'SnappyData Pulse': 'monitoring/monitoring.md'
    - 'Configuring High Availability for a Partitioned Table': 'monitoring/configure_high_availability.md'    
    - 'Configuring Logging': 'monitoring/configure_logging.md'
    - 'Getting Information from SnappyData System Tables': 'monitoring/monitor-manage.md'    
# -- Topic - Reference Guide
- 'Managing Security': 'security/security.md'
- 'Managing Security': 
    - 'Launching the Cluster in Secure Mode': 'security/launching_the_cluster_in_secure_mode.md'
    - 'Authentication - Connecting to a Secure Cluster': 'security/authentication_connecting_to_a_secure_cluster.md'
    - 'Authorization': 'security/authorization.md'
    - 'Configuring Network Encryption and Authentication using SSL': 'security/configuring_network_encryption_and_authentication_using_ssl.md'
    - 'User Names for Authentication, Authorization, and Membership': 'security/user_names_for_authentication_authorization_and_membership.md'
#- 'Evaluating Statistics for the System and Applications': 'vsd/system_performance.md'
#- 'Evaluating Statistics for the System and Applications':
#    - 'Collecting System Statistics': 'vsd/collecting_system_stats.md'
#    - 'Using VSD to Analyze Statistics': 'vsd/vsd_overview.md'
#    - 'Using VSD to Analyze Statistics':
#        - 'Installing and Running VSD': 'vsd/running_vsd.md'
#        - 'Transaction Performance': 'vsd/vsd_transactions.md'
#        - 'Table Performance': 'vsd/vsd_tables.md'
#        - 'SQL Statement Performance': 'vsd/vsd_statements.md'
#        - 'Memory Usage': 'vsd/vsd_memory.md'
#        - 'Client Connections': 'vsd/vsd-connection-stats.md'
#        - 'CPU Usage': 'vsd/vsd_cpu.md'
    - 'API Documentation': 'apidocsintro.md'
    - 'Configuring SSH Login without Password': 'reference/misc/passwordless_ssh.md'
    - 'Setting Up SnappyData ODBC Driver and Tableau Desktop': 'setting_up_odbc_driver-tableau_desktop.md'
    - 'Setting Up SnappyData JDBC Driver and QlikView': 'setting_up_jdbc_driver_qlikview.md'
- 'Troubleshooting Common Problems': 'troubleshooting/troubleshooting.md'
- 'Troubleshooting Common Problems':
    - 'Member startup problems': 'troubleshooting/member_startup_problems.md'
    - 'Recovering from a ConflictingPersistentDataException': 'troubleshooting/recovering_from_a_conflictingpersistentdataexception.md'
    - 'Preventing disk full errors': 'troubleshooting/preventing_disk_full_errors.md'
    - 'Recovering from disk full errors': 'troubleshooting/recovering_from_disk_full_errors.md'
    - 'Collecting logs, stats and dumps using the collect-debug-artifacts script': 'troubleshooting/collect_debug_artifacts.md'
    - 'Troubleshooting error messages': 'troubleshooting/troubleshooting_error_messages.md'  
- Community Edition/ Enterprise Edition Features: additional_files/open_source_components.md
- 'License Model': 'additional_files/license_model.md'
#- 'Release Notes': 'release_notes/release_notes.md'
#- 'Release Notes': 
#    - 'Known Issues': 'release_notes/known_issues.md'
- Contact and Support: techsupport.md
- License: LICENSE.md

theme: readthedocs
theme_dir: 'docs/custom_theme'

markdown_extensions:
  - admonition
  - toc:
      permalink: Link
      
extra_javascript:
    - 'js/menu.js'
    - 'js/highlight.pack.js'

extra_css:
    - 'css/toc.css'
    - 'css/menu.css'
    - 'css/images.css'
    - 'css/style.css'
    - 'css/highlight.css'
    - 'extra.css'
    
#plugins:
#    - search
    
copyright: Copyright &copy; 2018 SnappyData Inc.
