site_name: SnappyData GA RELEASE
site_url: http://www.snappydata.io
site_description: Project documentation for SnappyData.
site_author: SnappyData Team
site_favicon: favicon.ico

repo_url: https://github.com/SnappyDataInc/snappydata

pages:

- 'Welcome': 'index.md'
- 'About SnappyData': 'intro/about.md'
- 'About SnappyData':
    - 'Key Features': 'intro/key_features.md'
    - 'Extensions to the Spark Runtime': 'intro/extension_to_the_spark_runtime.md'
    - 'Spark Challenges for Mixed Workloads (OLTP, OLAP)': 'intro/oltp_olap.md'
    - 'Architecture': 'architecture.md'
    - 'Architecture':
        - 'Core Components': 'architecture/core_components.md'
        - 'Data Ingestion Pipeline': 'architecture/data_ingestion_pipeline.md'
        - 'Hybrid Cluster Manager': 'architecture/hybrid_cluster_manager.md'
# -- Topic - Quick Start
- 'Quick Start': 'quickstart.md'
- 'Quick Start':
    - 'Option 1- Getting Started with your Spark Distribution': 'quick_start/option1.md'
    - 'Option 2- Getting Started Using Spark Scala APIs': 'quick_start/option2.md'
    - 'Option 3- 20X Faster than Spark 2.0.2 Caching': 'quick_start/option3.md'
    - 'Option 4- Getting Started using SQL': 'quick_start/option4.md'
    - 'Option 5- Getting Started by Installing SnappyData On-Premise': 'quick_start/option5.md'    
    - 'Option 6- Getting Started on AWS': 'quick_start/option6.md'
    - 'Option 7- Getting Started with Docker Image': 'quick_start/option7.md'
# -- Topic - Installation and Sys Config
- 'Installation': 'install.md'
- 'Installation':
    - 'System Requirements': 'sys_requirement.md'
    #- 'System Requirements':
        #- Supported Configurations: 'sys_requirement/supported_configurations.md'
        #- Host Machine Requirements: 'sys_requirement/host_machine_requirements.md'
        #- Increase Unicast Buffer Size on Linux Platforms: 'sys_requirement/increase_unicast_buffer_size.md'
        #- Disable SYN Cookies on Linux Platforms: 'sys_requirement/disable_cookies.md'
        #- Filesystem Type for Linux Platforms: 'sys_requirement/filesystem_type.md'
        #- SnappyData Dashboard Requirements: 'sys_requirement/snappydata_dashboard.md'
    - 'Download and Install': 'empty.md'
    - 'Download and Install':
        - 'On Premise': 'install/on_premise.md'     
        - 'Building from Source': 'install/from_source.md'     
        - 'Cloud Installation': 'install/on_aws.md'     
# -- Topic - Cloud Services
- 'Snappy Cloud Services': 'cloud/cloud_services.md'
- 'Snappy Cloud Services':
    - 'Sub-Heading': 'empty.md'
# -- Topic - Concepts and Theories
- 'Concepts': 'concepts.md'
- 'Concepts':
    - 'Affinity Modes': 'deployment.md'
    - 'Affinity Modes': 
        - 'Local Mode': 'concepts/affinity_mode/local_mode.md'
        - 'Embedded SnappyData Store Mode': 'concepts/affinity_mode/embedded_mode.md'
        - 'SnappyData Smart Connector Mode': 'concepts/affinity_mode/smartconnector_mode.md'  
    - 'Tables': 'manage_data.md'
    - 'Tables':    
        - 'Table Types': 'concepts/tables/table_types.md'
        - 'Distributed Model: Partitioned vs Replicated Tables': 'concepts/tables/partitioned_tables.md'
        - 'Storage Model: Column vs Row Tables': 'concepts/tables/replicated_tables.md'
        - 'Evicting Table Data from Memory': 'concepts/tables/evicting_table_data_from_memory.md'
        - 'Persisting Table Data to SnappyData Disk Stores': 'concepts/tables/persisting_table_data_to_diskstores.md' 
        - 'Managing Tables in Memory': 'concepts/tables/managing_table_in_memory.md' 
        - 'Overview of Disk Stores': 'concepts/tables/disk_stores.md'  
        - 'Additional Topics': 'concepts/tables/estimating_heap_overhead.md'
    - 'Working with heterogenous data': 'empty.md'
    - 'Backup and Recovery': 'backup.md'
    - 'Backup and Recovery':
        - 'Online and offline backup and recovery': 'concepts/backup/online_offline_backup.md'
        - 'Redundancy and Data Availability for Failures': 'concepts/backup/redundancy_data_availability.md'
        - 'Recovering from Failures and Revoking Safely': 'concepts/backup/recovery_revoking.md'
        - 'Recovery using data extractor; data redundancy implications': 'concepts/backup/recovery_using_data_extractor_redundancy.md'
    - 'Developing Applications': 'developing_applications.md'
    - 'Developing Applications': 
        - 'Configuring SnappyData as a JDBC Datasource': 'concepts/developing_applications/configuring-JDBC_datasource.md'
        - 'Understanding the Data Consistency Model': 'concepts/developing_applications/understanding_the_data_consistency.md'
        - 'Using Distributed Transactions in Your Applications': 'concepts/developing_applications/using_distributed_transactions.md'
        - 'Connecting Java Clients and Peers': 'concepts/developing_applications/connecting_java_clients_and_peers.md'
        - 'Using Result Sets and Cursors': 'concepts/developing_applications/using_result_sets_and_cursors.md'
        - 'Storing and Loading JAR Files': 'concepts/developing_applications/storing_and_loading_jar_files.md'
        - 'Import Export': 'empty.md'
    - 'Synopsis Data Engine (SDE)': aqp.md
    - 'Synopsis Data Engine (SDE)':    
        - 'Key Concepts': 'concepts/sde/key_concepts.md'
        - 'Working with Stratified Sampling': 'concepts/sde/stratified_sampling.md'
        - 'Running Queries': 'concepts/sde/running_queries.md'
        - 'Examples': 'concepts/sde/examples.md'
        - 'Sample Selection': 'concepts/sde/sample_selection.md'
        - 'High Level Accuracy Contracts (HAC)': 'concepts/sde/hac.md'
        - 'Sketching': 'concepts/sde/sketching.md'
        - 'Using SDE': 'concepts/sde/using_sde.md'
    - 'iSight-Cloud': 'aqp_aws.md'
    - 'iSight-Cloud':
        - 'Setting up SnappyData Cloud Cluster': 'concepts/isight/setting_up_cloud_cluster.md'
        - 'Loading Data from AWS S3': 'concepts/isight/loading_data_s3.md'
        - 'Using Apache Zeppelin': 'concepts/isight/apache_zeppelin.md'
        - 'Using the Interpreter': 'concepts/isight/using_interpreter.md'
        - 'Using Predefined Notebooks': 'concepts/isight/predefined_notebooks.md'
        - 'Creating Notebooks - Try it yourself!': 'concepts/isight/creating_notebooks.md'
        - 'Monitoring SnappyData Cloud Cluster': 'concepts/isight/monitoring_cloud_cluster.md'
        - 'The Technology Powering iSight Cloud': 'concepts/isight/technology.md'
# -- Topic - Best Practises
- 'Best Practises': 'best_practises.md'
- 'Best Practises':
    - 'Using Index': 'best_practises/using_index.md'
    - 'Using Collocated Joins': 'best_practises/collocated_joins.md'
    - 'Using Char or Varchar string': 'best_practises/char_varchar_string.md'
    - 'Physical designing with SnappyData': 'best_practises/physical_design.md'
    - 'Using Row vs Column Tables': 'best_practises/use_row_column_table.md'
    - 'Right Affinity Mode to Use': 'best_practises/affinity_mode_to_use.md'
    - 'Capacity Planning': 'best_practises/capacity_planning.md'
    - 'Design Database and Schema': 'design_schema.md'
    - 'Design Database and Schema': 
        - 'Physical Design': 'best_practises/design_schema/physical_design.md'
        - 'Using Row and Column Table': 'best_practises/design_schema/row_column_table.md'
        - 'Design Priciples of Scalable': 'best_practises/design_schema/principles_of_scalable.md'
        - 'Identify Entity Groups and Partioning Keys': 'best_practises/design_schema/entity_group_partitioning_keys.md'
        - 'Replicate Dimension Tables': 'best_practises/design_schema/replicate_dimension_tables.md'
        - 'Example for Adapting Database Schema for SnappyData': 'best_practises/design_schema/adapting_database_scheme.md'
        - 'Dealing with Many-to-Many Relationships': 'best_practises/design_schema/many-to-many-relationship.md'
# -- Topic - How Tos
- 'How Tos': 'howto.md'
- 'How Tos':
    - 'How to Start a SnappyData Cluster': 'how_to/start_snappydata_cluster.md'
    - 'How to Run Spark Job inside the Cluster': 'how_to/run_spark_job_inside_the_cluster.md'
    - 'How to Access SnappyData Store from existing Spark Installation using Smart Connector': 'how_to/access_snappydata_store.md'
    - 'How to Use SnappyData SQL shell (snappy-shell)': 'how_to/use_sql_shell.md'
    - 'How to Create Row Tables and Run Queries': 'how_to/create_row_tables_and_run_queries.md'
    - 'How to Create Column Tables and Run Queries': 'how_to/create_column_tables_and_run_queries.md'
    - 'How to Load Data in SnappyData Tables': 'how_to/load_data_in_snappydata_tables.md'
    - 'How to Perform a Collocated Join': 'how_to/perform_a_collocated_join.md'
    - 'How to Connect using JDBC Driver': 'how_to/connect_using_jdbc_driver.md'
    - 'How to Store and Query JSON Objects': 'how_to/store_and_query_json_objects.md'
    - 'How to Store and Query Objects': 'how_to/store_and_query_objects.md'
    - 'How to Use Stream Processing with SnappyData': 'how_to/use_stream_processing.md'
    - 'How to Use Synopsis Data Engine to Run Approximate Queries': 'how_to/use_synopsis_data_engine.md'
    - 'How to Use Python to Create Tables and Run Queries': 'how_to/use_python_to_create_tables_and_run_queries.md'
# -- Topic - Configuration - Cluster and Others
- 'Configuration': 'configuration.md'
- 'Configuration': 
    - 'Configuration Files': 'configuring_cluster/configuration_files.md'
    - 'HDFS with SnappyData Store': 'configuring_cluster/hdfs_with_snappydata_store.md'
    - 'Spark Specific Properties': 'configuring_cluster/spark_specific_properties.md'
    - 'Example for Multiple-Host Configuration': 'configuring_cluster/example_for_multiple-host.md'
    - 'Environment Settings': 'configuring_cluster/environment_settings.md'
    - 'Hadoop Provided Settings': 'configuring_cluster/hadoop_provided_settings.md'
    - 'Per Component Configuration': 'configuring_cluster/per_component_configuration.md'
    - 'Add Servers to the Cluster and Stop Servers': 'configuring_cluster/add_and_stop_servers.md'
    - 'Starting Members Individually using Command Line (without scripts)': 'configuring_cluster/starting_members_individually_cli.md'
    - 'Logging': 'configuring_cluster/logging.md'    
# -- Topic - Montioring Dashboard
- 'Managing and Monitoring': 'monitoring.md'
- 'Managing and Monitoring': 
    - 'Topics to Decide': 'empty.md'
# -- Topic - Troubleshooting
- 'Troubleshooting and Analysis': 'troubleshooting.md'
- 'Troubleshooting and Analysis': 
    - 'Getting thread dumps from GUI or detailed stacks using SIGURG': 'troubleshooting/thread_dumps.md'
    - 'Collocating logs and stats using collect-debug-artifacts.sh': 'troubleshooting/collocating_logs.md'
    - 'Using VSD (can we make use of GemFire VSD docs?)': 'troubleshooting/using_vsd.md'
    - 'Enabling/disabling logging levels/traces on-the-fly': 'troubleshooting/logging_levels.md'
    - 'Cannot connect using EC2 Scripts': 'troubleshooting/connect_ec2_scripts.md'
    - 'Increase memory for Spark executors': 'troubleshooting/increase_memory.md'
    - 'Can I read orc files from snappy-shell?': 'troubleshooting/read_orc_files.md'
    - 'Observing logs for warning/severe/errors and decoding log messages': 'troubleshooting/observing_logs.md'
# -- Topic - SQL Reference Guide
- 'SnappyData SQL Reference Guide': 'sql_reference.md'
- 'SnappyData SQL Reference Guide': 
    - 'Statements': 'sql_reference/statements.md'
    - 'Procedures': 'sql_reference/procedures.md'   
# -- Topic - Glossary
- 'Glossary': 'glossary/glossary.md'
# -- Topic - About and Contact
- 'About': 'empty.md'
- 'About': 
    - 'Contact and Support': 'techsupport.md'
    - 'License': 'LICENSE.md'
theme: readthedocs
theme_dir: 'docs/custom_theme'

extra_javascript:
  - 'js/menu.js'
  
extra_css:
    - 'css/toc.css'
    - 'css/menu.css'
    - 'css/images.css'
    - 'css/style.css'
    - 'extra.css'
markdown_extensions:
    - admonition:

copyright: Copyright &copy; 2017 SnappyData Inc.
