site_name: SnappyData GA RELEASE
site_url: http://www.snappydata.io
site_description: Project documentation for SnappyData.
site_author: SnappyData Team
site_favicon: favicon.ico

repo_url: https://github.com/SnappyDataInc/snappydata

pages:
# this file may just be the [toc] tag .. not sure if that works.
#
- 'Home': 'index.md'
- 'Overview': 'empty.md'
- 'Overview': 
    - 'Key Features': 'intro/key_features.md'
    - 'Extensions to the Spark Runtime': 'intro/extension_to_the_spark_runtime.md'
    - 'Spark Challenges for Mixed Workloads (OLTP, OLAP)': 'intro/oltp_olap.md'
# -- Topic - Quick Start
- 'Quick Start': 'quickstart.md'
- 'Quick Start':
    - 'Option 1- Getting Started with your Spark Distribution': 'quick_start/option1.md'
    - 'Option 2- Getting Started Using Spark Scala APIs': 'quick_start/option2.md'
    - 'Option 3- 20X Faster than Spark 2.0.2 Caching': 'quick_start/option3.md'
    - 'Option 4- Getting Started using SQL': 'quick_start/option4.md'
    - 'Option 5- Getting Started by Installing SnappyData On-Premise': 'quick_start/option5.md'    
    - 'Option 6- Getting Started on AWS': 'quick_start/option6.md'
    - 'Option 7- Getting Started with Docker Image': 'quick_start/option7.md'
# -- Topic - Installation and Sys Config
- 'Installation': 'install.md'
- 'Installation':
    - 'System Requirements': 'sys_requirement.md'
    - 'System Requirements':
        - Supported Configurations: 'sys_requirement/supported_configurations.md'
        - Host Machine Requirements: 'sys_requirement/host_machine_requirements.md'
        - Increase Unicast Buffer Size on Linux Platforms: 'sys_requirement/increase_unicast_buffer_size.md'
        - Disable SYN Cookies on Linux Platforms: 'sys_requirement/disable_cookies.md'
        - Filesystem Type for Linux Platforms: 'sys_requirement/filesystem_type.md'
        - SnappyData Dashboard Requirements: 'sys_requirement/snappydata_dashboard.md'
    - 'Download and Install': 'empty.md'
    - 'Download and Install':
        - 'On Premise': 'install/on_premise.md'     
        - 'Building from Source': 'install/from_source.md'     
        - 'Cloud Installation': 'install/on_aws.md'     
# -- Topic - Cloud Services
- 'Snappy Cloud Services': 'empty.md'
- 'Snappy Cloud Services':
    - 'Sub-Heading': 'empty.md'
# -- Topic - Concepts and Theories
- 'Concepts': 'empty.md'
- 'Concepts':
    - 'Sub-Heading': 'empty.md'
# -- Topic - Best Practises
- 'Best Practises': 'best_practises.md'
- 'Best Practises':
    - Using Index: 'best_practises/using_index.md'
    - Using Collocated Joins: 'best_practises/collocated_joins.md'
    - Using Char or Varchar string: 'best_practises/char_varchar_string.md'
    - Physical designing with SnappyData: 'best_practises/physical_design.md'
    - Using Row vs Column Tables : 'best_practises/use_row_column_table.md'
    - Right Affinity Mode to Use : 'best_practises/affinity_mode_to_use.md'
    - Capacity Planning : 'best_practises/capacity_planning.md'
# -- Topic - How Tos
- 'How Tos': 'howto.md'
- 'How Tos':
    - 'How to Start a SnappyData Cluster': 'how_to/start_snappydata_cluster.md'
    - 'How to Run Spark Job inside the Cluster': 'how_to/run_spark_job_inside_the_cluster.md'
    - 'How to Access SnappyData Store from existing Spark Installation using Smart Connector': 'how_to/access_snappydata_store.md'
    - 'How to Use SnappyData SQL shell (snappy-shell)': 'how_to/use_sql_shell.md'
    - 'How to Create Row Tables and Run Queries': 'how_to/create_row_tables_and_run_queries.md'
    - 'How to Create Column Tables and Run Queries': 'how_to/create_column_tables_and_run_queries.md'
    - 'How to Load Data in SnappyData Tables': 'how_to/load_data_in_snappydata_tables.md'
    - 'How to Perform a Collocated Join': 'how_to/perform_a_collocated_join.md'
    - 'How to Connect using JDBC Driver': 'how_to/connect_using_jdbc_driver.md'
    - 'How to Store and Query JSON Objects': 'how_to/store_and_query_json_objects.md'
    - 'How to Store and Query Objects': 'how_to/store_and_query_objects.md'
    - 'How to Use Stream Processing with SnappyData': 'how_to/use_stream_processing.md'
    - 'How to Use Synopsis Data Engine to Run Approximate Queries': 'how_to/use_synopsis_data_engine.md'
    - 'How to Use Python to Create Tables and Run Queries': 'how_to/use_python_to_create_tables_and_run_queries.md'
# -- Topic - Configuration - Cluster and Others
- 'Configuration': 'configuration.md'
- 'Configuration': 
    - 'Configuration Files': 'configuring_cluster/configuration_files.md'
    - 'HDFS with SnappyData Store': 'configuring_cluster/hdfs_with_snappydata_store.md'
    - 'Spark Specific Properties': 'configuring_cluster/spark_specific_properties.md'
    - 'Example for Multiple-Host Configuration': 'configuring_cluster/example_for_multiple-host.md'
    - 'Environment Settings': 'configuring_cluster/environment_settings.md'
    - 'Hadoop Provided Settings': 'configuring_cluster/hadoop_provided_settings.md'
    - 'Per Component Configuration': 'configuring_cluster/per_component_configuration.md'
    - 'Add Servers to the Cluster and Stop Servers': 'configuring_cluster/add_and_stop_servers.md'
    - 'Starting Members Individually using Command Line (without scripts)': 'configuring_cluster/starting_members_individually_cli.md'
    - 'Logging': 'configuring_cluster/logging.md'    
# -- Topic - Montioring Dashboard
- 'Managing and Monitoring': 'monitoring.md'
- 'Managing and Monitoring': 
    - 'Topics to Decide': 'empty.md'
# -- Topic - Synopsis Data Engine
- 'Synopsis Data Engine (SDE)': aqp.md
- 'Synopsis Data Engine (SDE)':    
    - 'Key Concepts': 'sde/key_concepts.md'
    - 'Working with Stratified Sampling': 'sde/stratified_sampling.md'
    - 'Running Queries': 'sde/running_queries.md'
    - 'Examples': 'sde/examples.md'
    - 'Sample Selection': 'sde/sample_selection.md'
    - 'High Level Accuracy Contracts (HAC)': 'sde/hac.md'
    - 'Sketching': 'sde/sketching.md'
    - 'Using SDE': 'sde/using_sde.md'
# -- Topic - Troubleshooting
- 'Troubleshooting and Analysis': 'troubleshooting.md'
- 'Troubleshooting and Analysis': 
    - 'Getting thread dumps from GUI or detailed stacks using SIGURG': 'troubleshooting/thread_dumps.md'
    - 'Collocating logs and stats using collect-debug-artifacts.sh': 'troubleshooting/collocating_logs.md'
    - 'Using VSD (can we make use of GemFire VSD docs?)': 'troubleshooting/using_vsd.md'
    - 'Enabling/disabling logging levels/traces on-the-fly': 'troubleshooting/logging_levels.md'
    - 'Cannot connect using EC2 Scripts': 'troubleshooting/connect_ec2_scripts.md'
    - 'Increase memory for Spark executors': 'troubleshooting/increase_memory.md'
    - 'Can I read orc files from snappy-shell?': 'troubleshooting/read_orc_files.md'
    - 'Observing logs for warning/severe/errors and decoding log messages': 'troubleshooting/observing_logs.md'
# -- Topic - SQL Reference Guide
- 'SQL Reference Guide': 'sql_reference.md'
- 'SQL Reference Guide': 
    - 'Statements': 'sql_reference/statements.md'
    - 'Functions': 'sql_reference/functions.md'
    - 'Procedures': 'sql_reference/procedures.md'   
# -- Topic - Glossary
- 'Glossary': 'glossary/glossary.md'
# -- Topic - About and Contact
- 'About': 'empty.md'
- 'About': 
    - 'Contact and Support': 'techsupport.md'
    - 'License': 'LICENSE.md'
theme: readthedocs
theme_dir: 'docs/custom_theme'

extra_javascript:
  - 'js/menu.js'
  
extra_css:
    - 'css/toc.css'
    - 'css/menu.css'
    - 'css/images.css'
    - 'css/style.css'
    - 'extra.css'
markdown_extensions:
    - admonition:

copyright: Copyright &copy; 2017 SnappyData Inc.
